<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BoardUniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('board_university')->truncate();
        $data = [
            ['name' => 'Federal Board of Intermediate and Secondary Education (FBISE)'],
            ['name' => 'BISE Lahore'],
            ['name' => 'BISE Rawalpindi'],
            ['name' => 'BISE Gujranwala'],
            ['name' => 'BISE Faisalabad'],
            ['name' => 'BISE Multan'],
            ['name' => 'BISE Sargodha'],
            ['name' => 'BISE Bahawalpur'],
            ['name' => 'BISE Dera Ghazi Khan'],
            ['name' => 'BISE Sahiwal'],
            ['name' => 'BISE Karachi'],
            ['name' => 'BISE Hyderabad'],
            ['name' => 'BISE Sukkur'],
            ['name' => 'BISE Mirpurkhas'],
            ['name' => 'BISE Larkana'],
            ['name' => 'BISE Peshawar'],
            ['name' => 'BISE Swat'],
            ['name' => 'BISE Kohat'],
            ['name' => 'BISE Malakand'],
            ['name' => 'BISE Abbottabad'],
            ['name' => 'BISE Bannu'],
            ['name' => 'BISE Mardan'],
            ['name' => 'BISE Dera Ismail Khan'],
            ['name' => 'BISE Quetta'],
            ['name' => 'BISE Mirpur (AJK)'],
            ['name' => 'Abasyn University, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'Abdul Wali Khan University Mardan, Mardan, Khyber Pakhtunkhwa'],
            ['name' => 'Aga Khan University, Karachi, Sindh'],
            ['name' => 'Air University, Islamabad, Federal Capital'],
            ['name' => 'Allama Iqbal Open University, Islamabad, Federal Capital'],
            ['name' => 'Alhamd Islamic University, Quetta, Balochistan'],
            ['name' => 'Bacha Khan University, Charsadda, Khyber Pakhtunkhwa'],
            ['name' => 'Bahauddin Zakariya University, Multan, Punjab'],
            ['name' => 'Bahria University, Islamabad, Federal Capital'],
            ['name' => 'Balochistan University of Engineering and Technology, Khuzdar, Balochistan'],
            ['name' => 'Balochistan University of Information Technology, Engineering and Management Sciences, Quetta, Balochistan'],
            ['name' => 'Benazir Bhutto Shaheed University Lyari, Karachi, Sindh'],
            ['name' => 'Cadet College Petaro, Petaro, Sindh'],
            ['name' => 'COMSATS Institute of Information Technology, Islamabad, Federal Capital'],
            ['name' => 'Dow University of Health Sciences, Karachi, Sindh'],
            ['name' => 'Fatima Jinnah Medical University, Lahore, Punjab'],
            ['name' => 'Federal Urdu University of Arts, Science and Technology, Karachi, Sindh'],
            ['name' => 'Forman Christian College, Lahore, Punjab'],
            ['name' => 'Ghulam Ishaq Khan Institute of Engineering Sciences and Technology, Topi, Khyber Pakhtunkhwa'],
            ['name' => 'Government College University Faisalabad, Faisalabad, Punjab'],
            ['name' => 'Government College University Lahore, Lahore, Punjab'],
            ['name' => 'Hajvery University, Lahore, Punjab'],
            ['name' => 'Hazara University, Mansehra, Khyber Pakhtunkhwa'],
            ['name' => 'HITEC University, Taxila, Punjab'],
            ['name' => 'Imperial College of Business Studies, Lahore, Punjab'],
            ['name' => 'Information Technology University, Lahore, Punjab'],
            ['name' => 'Institute of Business Administration, Karachi, Sindh'],
            ['name' => 'Institute of Management Sciences, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'Institute of Space Technology, Islamabad, Federal Capital'],
            ['name' => 'International Islamic University, Islamabad, Federal Capital'],
            ['name' => 'Iqra National University, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'Islamia College University, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'Islamic International Medical College, Rawalpindi, Punjab'],
            ['name' => 'Islamic University of Bahawalpur, Bahawalpur, Punjab'],
            ['name' => 'Jinnah Sindh Medical University, Karachi, Sindh'],
            ['name' => 'Karakoram International University, Gilgit, Gilgit-Baltistan'],
            ['name' => 'Khyber Medical University, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'King Edward Medical University, Lahore, Punjab'],
            ['name' => 'Kinnaird College for Women, Lahore, Punjab'],
            ['name' => 'Lahore College for Women University, Lahore, Punjab'],
            ['name' => 'Lahore School of Economics, Lahore, Punjab'],
            ['name' => 'Lahore University of Management Sciences, Lahore, Punjab'],
            ['name' => 'Lasbela University of Agriculture, Water and Marine Sciences, Uthal, Balochistan'],
            ['name' => 'Mehran University of Engineering and Technology, Jamshoro, Sindh'],
            ['name' => 'Minhaj University Lahore, Lahore, Punjab'],
            ['name' => 'Mirpur University of Science and Technology, Mirpur, Azad Kashmir'],
            ['name' => 'Muhammad Ali Jinnah University, Karachi, Sindh'],
            ['name' => 'Muhammad Nawaz Sharif University of Engineering & Technology, Multan, punjab'],
            ['name' => 'Muhammad Nawaz Sharif University of Agriculture, Multan, punjab'],
            ['name' => 'National Defence University, Islamabad, Federal Capital'],
            ['name' => 'National University of Computer and Emerging Sciences, Islamabad, Federal Capital'],
            ['name' => 'National University of Modern Languages, Islamabad, Federal Capital'],
            ['name' => 'National University of Sciences and Technology, Islamabad, Federal Capital'],
            ['name' => 'NED University of Engineering and Technology, Karachi, Sindh'],
            ['name' => 'Nishtar Medical College, Multan, Punjab'],
            ['name' => 'NUR International University, Lahore, Punjab'],
            ['name' => 'Pakistan Institute of Development Economics, Islamabad, Federal Capital'],
            ['name' => 'Pakistan Institute of Engineering and Applied Sciences, Islamabad, Federal Capital'],
            ['name' => 'Pakistan Military Academy, Abbottabad, Khyber Pakhtunkhwa'],
            ['name' => 'Pakistan Naval Academy, Karachi, Sindh'],
            ['name' => 'Peoples University of Medical and Health Sciences for Women, Nawabshah, Sindh'],
            ['name' => 'Preston University, Karachi, Sindh'],
            ['name' => 'Quaid-e-Azam University, Islamabad, Federal Capital'],
            ['name' => 'Quetta Institute of Medical Sciences, Quetta, Balochistan'],
            ['name' => 'Rawalpindi Medical University, Rawalpindi, Punjab'],
            ['name' => 'Riphah International University, Islamabad, Federal Capital'],
            ['name' => 'Shaheed Benazir Bhutto Women University, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'Shaheed Mohtarma Benazir Bhutto Medical University, Larkana, Sindh'],
            ['name' => 'Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology, Karachi, Sindh'],
            ['name' => 'Shalamar Medical and Dental College, Lahore, Punjab'],
            ['name' => 'Sindh Madressatul Islam University, Karachi, Sindh'],
            ['name' => 'Sindh Medical College, Karachi, Sindh'],
            ['name' => 'Sir Syed University of Engineering and Technology, Karachi, Sindh'],
            ['name' => 'Sukkur Institute of Business Administration, Sukkur, Sindh'],
            ['name' => 'Superior University, Lahore, Punjab'],
            ['name' => 'University of Agriculture, Faisalabad, Faisalabad, Punjab'],
            ['name' => 'University of Azad Jammu and Kashmir, Muzaffarabad, Azad Kashmir'],
            ['name' => 'University of Balochistan, Quetta, Balochistan'],
            ['name' => 'University of Central Punjab, Lahore, Punjab'],
            ['name' => 'University of Engineering and Technology, Lahore, Lahore, Punjab'],
            ['name' => 'University of Engineering and Technology, Peshawar, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'University of Faisalabad, Faisalabad, Punjab'],
            ['name' => 'University of Gujrat, Gujrat, Punjab'],
            ['name' => 'University of Health Sciences, Lahore, Lahore, Punjab'],
            ['name' => 'University of Karachi, Karachi, Sindh'],
            ['name' => 'University of Lahore, Lahore, Punjab'],
            ['name' => 'University of Management and Technology, Lahore, Punjab'],
            ['name' => 'University of Peshawar, Peshawar, Khyber Pakhtunkhwa'],
            ['name' => 'University of Punjab, Lahore, Punjab'],
            ['name' => 'University of Sargodha, Sargodha, Punjab'],
            ['name' => 'University of Sindh, Jamshoro, Sindh'],
            ['name' => 'University of South Asia, Lahore, Punjab'],
            ['name' => 'University of Swat, Swat, Khyber Pakhtunkhwa'],
            ['name' => 'University of the Punjab, Lahore, Punjab'],
            ['name' => 'University of Veterinary and Animal Sciences, Lahore, Punjab'],
            ['name' => 'Virtual University of Pakistan, Lahore, Punjab'],
            ['name' => 'Women University Multan, Multan, Punjab'],
            ['name' => 'Ziauddin University, Karachi, Sindh'],
            ['id' => 124, 'name' => 'Other']
        ];

        foreach ($data as $item) {
            DB::table('board_university')->insert([
                'name' => $item['name'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]);
        }
    }
}
